name: Laravel CI with PostgreSQL

on:
  push:
    branches: [ main ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          DB_DATABASE: acc_communication
          DB_USERNAME: postgres
          DB_PASSWORD: 12345678
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1.0
          extensions: mbstring, pdo, pgsql, ctype, iconv, zip, dom

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      # Set up testing environment
      - name: Prepare .env
        run: cp .env.example .env

      - name: Generate key
        run: php artisan key:generate

      - name: Run migrations
        env:
          DB_CONNECTION: pgsql
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
          DB_DATABASE: acc_communication
          DB_USERNAME: postgres
          DB_PASSWORD: 12345678
        run: php artisan migrate --force

      # Run tests
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: pgsql
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
          DB_DATABASE: acc_communication
          DB_USERNAME: postgres
          DB_PASSWORD: 12345678
        run: vendor/bin/phpunit
